### ISSUE TITLE
[FEATURE] show example in docs?

### ISSUE THREAD

**Issue by itsramiel** [TheWidlarzGroup/react-native-notification#109]
It would be nice to add gifs of examples in main page for people to know how it behaves/looks. Would that be possible?

**Comment by danielmark0116** [comment]
Hi , thanks for suggestion :) 👍🏽 

You can take a look at the default variants here (screenshots) before we add some GIF previews: [Default Variants](https://thewidlarzgroup.github.io/react-native-notificated/docs/default-variants-config/default-variants)

**Comment by PdoubleU** [comment]
Hi @itsramiel, how's it going?

Have you been using react-native-notificated recently? :)

Do you have any thoughts on what can be improved? 🤔
